services:
  recipe-frontend:
    build: .
    container_name: recipe-frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
    # command: npm run dev
    restart: on-failure
    # depends_on:
    #   - recipe-backend
